# Based on ./operator/attestation-key-register/Containerfile
# SPDX-FileCopyrightText: Alice Frosi <afrosi@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

ARG build_type
FROM quay.io/redhat-user-workloads/cocl-operator-tenant/buildroot:latest AS builder
ARG build_type
WORKDIR /build

# Drift detection - ensure local build matches upstream
COPY drift-detection/detector.sh /detector.sh
COPY drift-cache /drift-cache
WORKDIR /tmp
COPY operator/attestation-key-register/Containerfile .
RUN /detector.sh ./Containerfile /drift-cache/attestation-key-register/Containerfile

WORKDIR /build
COPY operator/Makefile operator/Cargo.toml operator/Cargo.lock operator/go.mod operator/go.sum ./
COPY operator/api api
COPY operator/lib lib
COPY operator/attestation-key-register/Cargo.toml attestation-key-register/
COPY operator/attestation-key-register/src/lib.rs attestation-key-register/src/

# Set only required crates as members to minimize rebuilds upon changes.
RUN sed -i 's/members =.*/members = ["lib", "attestation-key-register"]/' Cargo.toml && \
    make crds-rs

# In debug builds, build dependencies to avoid full rebuild.
RUN if [ "$build_type" = debug ]; then cargo build -p attestation-key-register; fi

COPY operator/attestation-key-register/src attestation-key-register/src
RUN cargo build -p attestation-key-register $(if [ "$build_type" = release ]; then echo --release; fi)

FROM registry.access.redhat.com/ubi9/ubi-minimal
ARG build_type
COPY --from=builder "/build/target/$build_type/attestation-key-register" /usr/bin
EXPOSE 8001
ENTRYPOINT ["/usr/bin/attestation-key-register"]
